# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ion/GitHome/LSDJam24

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ion/GitHome/LSDJam24

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/ion/GitHome/LSDJam24/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ion/GitHome/LSDJam24/CMakeFiles /home/ion/GitHome/LSDJam24//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ion/GitHome/LSDJam24/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/ion/GitHome/LSDJam24/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LSDJAM

# Build rule for target.
LSDJAM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LSDJAM
.PHONY : LSDJAM

# fast build rule for target.
LSDJAM/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/build
.PHONY : LSDJAM/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/CMakeFiles/uninstall.dir/build.make _deps/raylib-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build.make _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named Jolt

# Build rule for target.
Jolt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Jolt
.PHONY : Jolt

# fast build rule for target.
Jolt/fast:
	$(MAKE) $(MAKESILENT) -f _deps/jolt-build/CMakeFiles/Jolt.dir/build.make _deps/jolt-build/CMakeFiles/Jolt.dir/build
.PHONY : Jolt/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f _deps/spdlog-build/CMakeFiles/spdlog.dir/build.make _deps/spdlog-build/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glm-build/glm/CMakeFiles/glm.dir/build.make _deps/glm-build/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

# target to build an object file
cmake_pch.hxx.gch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/cmake_pch.hxx.gch
.PHONY : cmake_pch.hxx.gch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

sources/Core/GameObject.o: sources/Core/GameObject.cpp.o
.PHONY : sources/Core/GameObject.o

# target to build an object file
sources/Core/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Core/GameObject.cpp.o
.PHONY : sources/Core/GameObject.cpp.o

sources/Core/GameObject.i: sources/Core/GameObject.cpp.i
.PHONY : sources/Core/GameObject.i

# target to preprocess a source file
sources/Core/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Core/GameObject.cpp.i
.PHONY : sources/Core/GameObject.cpp.i

sources/Core/GameObject.s: sources/Core/GameObject.cpp.s
.PHONY : sources/Core/GameObject.s

# target to generate assembly for a file
sources/Core/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Core/GameObject.cpp.s
.PHONY : sources/Core/GameObject.cpp.s

sources/Core/Log.o: sources/Core/Log.cpp.o
.PHONY : sources/Core/Log.o

# target to build an object file
sources/Core/Log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Core/Log.cpp.o
.PHONY : sources/Core/Log.cpp.o

sources/Core/Log.i: sources/Core/Log.cpp.i
.PHONY : sources/Core/Log.i

# target to preprocess a source file
sources/Core/Log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Core/Log.cpp.i
.PHONY : sources/Core/Log.cpp.i

sources/Core/Log.s: sources/Core/Log.cpp.s
.PHONY : sources/Core/Log.s

# target to generate assembly for a file
sources/Core/Log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Core/Log.cpp.s
.PHONY : sources/Core/Log.cpp.s

sources/Player.o: sources/Player.cpp.o
.PHONY : sources/Player.o

# target to build an object file
sources/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Player.cpp.o
.PHONY : sources/Player.cpp.o

sources/Player.i: sources/Player.cpp.i
.PHONY : sources/Player.i

# target to preprocess a source file
sources/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Player.cpp.i
.PHONY : sources/Player.cpp.i

sources/Player.s: sources/Player.cpp.s
.PHONY : sources/Player.s

# target to generate assembly for a file
sources/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Player.cpp.s
.PHONY : sources/Player.cpp.s

sources/Systems/Systems.o: sources/Systems/Systems.cpp.o
.PHONY : sources/Systems/Systems.o

# target to build an object file
sources/Systems/Systems.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Systems/Systems.cpp.o
.PHONY : sources/Systems/Systems.cpp.o

sources/Systems/Systems.i: sources/Systems/Systems.cpp.i
.PHONY : sources/Systems/Systems.i

# target to preprocess a source file
sources/Systems/Systems.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Systems/Systems.cpp.i
.PHONY : sources/Systems/Systems.cpp.i

sources/Systems/Systems.s: sources/Systems/Systems.cpp.s
.PHONY : sources/Systems/Systems.s

# target to generate assembly for a file
sources/Systems/Systems.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/Systems/Systems.cpp.s
.PHONY : sources/Systems/Systems.cpp.s

sources/main.o: sources/main.cpp.o
.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i
.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s
.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSDJAM.dir/build.make CMakeFiles/LSDJAM.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... Jolt"
	@echo "... LSDJAM"
	@echo "... glfw"
	@echo "... glm"
	@echo "... raylib"
	@echo "... spdlog"
	@echo "... cmake_pch.hxx.gch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
	@echo "... sources/Core/GameObject.o"
	@echo "... sources/Core/GameObject.i"
	@echo "... sources/Core/GameObject.s"
	@echo "... sources/Core/Log.o"
	@echo "... sources/Core/Log.i"
	@echo "... sources/Core/Log.s"
	@echo "... sources/Player.o"
	@echo "... sources/Player.i"
	@echo "... sources/Player.s"
	@echo "... sources/Systems/Systems.o"
	@echo "... sources/Systems/Systems.i"
	@echo "... sources/Systems/Systems.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/ion/GitHome/LSDJam24/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

